openapi: 3.0.0
info:
  title: hotel
  version: '1.0'
  contact:
    name: masashi mizuno
  description: |-
    Hotel向けAPI
    認証はCognitoが発行したJWT Tokenを利用する
servers:
  - url: 'https://satellite-office-app.herokuapp.com'
    description: Mock
  - url: 'https://{本番ドメイン}/hotel/api/v1'
    description: Production
paths:
  /hotel/login:
    post:
      summary: ログイン
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  hotel_id:
                    type: number
                    description: ログインしたユーザーのID
                    example: 100
                  hotel_name:
                    type: string
                    description: ユーザー名
                    example: 鈴木太郎
                  token:
                    type: string
                    description: アクセストークン
                    format: string
                    example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
                required:
                  - hotel_id
                  - hotel_name
                  - token
              examples:
                Example:
                  value:
                    hotel_id: 1
                    hotel_name: ホテルA
                    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Ai
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-login
      description: Cognitoを利用した認証を行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 登録メールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - email
                - password
        description: ''
      tags:
        - 認証
    parameters: []
  /hotel/info:
    get:
      summary: ホテル情報
      tags:
        - ホテル
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: ホテルID
                  name:
                    type: string
                    description: ホテル名
                  name_kana:
                    type: string
                    description: ホテル名カナ
                  address:
                    type: string
                    description: 住所
                  tel:
                    type: string
                    description: 電話番号
                  contract_number:
                    type: string
                    description: 契約番号
                  url:
                    type: string
                    description: URL
                  area_id:
                    type: number
                    description: エリアコード
                  station:
                    type: string
                    description: 最寄り駅
                  access:
                    type: string
                    description: 交通アクセス
                  parking:
                    type: string
                    description: 駐車場
                  status:
                    type: number
                    description: |-
                      0: 停止
                      1: 利用可能
                required:
                  - id
                  - name
                  - name_kana
                  - address
                  - tel
                  - contract_number
                  - area_id
                  - status
              examples:
                example:
                  value:
                    id: 1
                    name: ホテルA
                    name_kane: ホテルエー
                    address: 東京都品川区
                    tel: 03-0000-1111
                    contract_number: JS-H-022790086075
                    url: 'https://xxx.com'
                    area_id: 100
                    station: 品川駅
                    access: ＪＲ線品川駅（高輪口）より徒歩２分
                    parking: '有り　1,500円（税込み）　先着順'
                    status: 1
      operationId: get-hotel-info
      description: ホテル情報取得API
      security:
        - bearerAuth: []
  /hotel/edit:
    post:
      summary: ホテル情報編集
      tags:
        - ホテル
      responses:
        '200':
          description: OK
      operationId: get-hotel-edit
      description: ホテル情報編集API
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ホテル名
                name_kana:
                  type: string
                  description: ホテル名カナ
                address:
                  type: string
                  description: 住所
                tel:
                  type: string
                  description: 電話番号
                url:
                  type: string
                  description: URL
                area_id:
                  type: number
                  description: エリアコード
                station:
                  type: string
                  description: 最寄り駅
                access:
                  type: string
                  description: 交通アクセス
                parking:
                  type: string
                  description: 駐車場
              required:
                - area_id
                - tel
                - address
                - name_kana
                - name
  /hotel/rooms:
    get:
      summary: 部屋一覧
      tags:
        - 部屋
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 部屋ID
                        name:
                          type: string
                          description: 部屋名
                        capacity:
                          type: string
                          description: 席数
                        price:
                          type: string
                          description: 単価
                        start_time:
                          type: string
                          description: 開始時間
                        end_time:
                          type: string
                          description: 終了時間
                        available_day_of_week:
                          type: object
                          description: 開放曜日
                          required:
                            - monday
                            - tuesday
                            - wednesday
                            - thursday
                            - friday
                            - saturday
                            - sunday
                          properties:
                            monday:
                              type: boolean
                            tuesday:
                              type: boolean
                            wednesday:
                              type: boolean
                            thursday:
                              type: boolean
                            friday:
                              type: boolean
                            saturday:
                              type: boolean
                            sunday:
                              type: boolean
                        non_open:
                          type: boolean
                          description: 非開放か
                        status:
                          type: number
                          description: '0: 停止 1: 利用可能'
                        order_number:
                          type: number
                          description: 表示順
                      required:
                        - id
                        - name
                        - capacity
                        - price
                        - start_time
                        - end_time
                        - available_day_of_week
                        - non_open
                        - status
                        - order_number
              examples:
                example:
                  value:
                    rooms:
                      - id: 1
                        name: 会議室A
                        capacity: 10
                        price: 200
                        start_time: '10:00'
                        end_time: '20:00'
                        available_day_of_week:
                          monday: true
                          tuesday: true
                          wednesday: false
                          thursday: true
                          friday: true
                          saturday: false
                          sunday: false
                        non_open: false
                        status: 1
                        order_number: 1
      operationId: get-hotel-rooms
      security:
        - bearerAuth: []
      description: 部屋一覧取得API
  '/hotel/rooms/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: 部屋ID
    get:
      summary: 部屋詳細
      tags:
        - 部屋
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 部屋ID
                  name:
                    type: string
                    description: 部屋名
                  location:
                    type: string
                    description: 館内場所
                  capacity:
                    type: string
                    description: 席数
                  price:
                    type: string
                    description: 単価
                  expiration_in:
                    type: string
                    description: 有効期限開始
                  expiration_out:
                    type: string
                    description: 有効期限終了
                  start_time:
                    type: string
                    description: 開始時間
                  end_time:
                    type: string
                    description: 終了時間
                  available_day_of_week:
                    type: object
                    description: 開放曜日
                    required:
                      - monday
                      - tuesday
                      - wednesday
                      - thursday
                      - friday
                      - saturday
                      - sunday
                    properties:
                      monday:
                        type: boolean
                      tuesday:
                        type: boolean
                      wednesday:
                        type: boolean
                      thursday:
                        type: boolean
                      friday:
                        type: boolean
                      saturday:
                        type: boolean
                      sunday:
                        type: boolean
                  reservation_start_date:
                    type: number
                    description: 予約開始日
                  equipment:
                    type: string
                    description: 設備
                  non_open:
                    type: boolean
                    description: 非開放か
                  status:
                    type: number
                    description: '0: 停止 1: 利用可能'
                  order_number:
                    type: number
                    description: 表示順
                required:
                  - id
                  - name
                  - capacity
                  - price
                  - start_time
                  - end_time
                  - available_day_of_week
                  - non_open
                  - status
                  - order_number
              examples:
                example:
                  value:
                    id: 1
                    name: 会議室A
                    location: 本館２階　フロント横
                    capacity: 10
                    price: 200
                    start_time: '10:00'
                    end_time: '20:00'
                    available_day_of_week:
                      monday: true
                      tuesday: true
                      wednesday: false
                      thursday: true
                      friday: true
                      saturday: false
                      sunday: false
                    non_open: false
                    status: 1
                    order_number: 1
                    expiration_in: 2020/01/01
                    expiration_out: 2020/05/20
                    reservation_start_date: 10
                    equipment: インターネット接続無料（有線・無線） / コンセント / プリンター / ロッカー / 自動販売機 / 喫煙所
      operationId: get-hotel-rooms-id
      description: 部屋詳細API
      security:
        - bearerAuth: []
  /hotel/rooms/add:
    post:
      summary: 部屋追加・編集
      tags:
        - 部屋
      responses:
        '200':
          description: OK
      operationId: post-hotel-rooms-add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: |-
                    部屋ID
                    なければ新規・あれば編集
                name:
                  type: string
                  description: 部屋名
                location:
                  type: string
                  description: 館内場所
                capacity:
                  type: string
                  description: 席数
                price:
                  type: string
                  description: 単価
                expiration_in:
                  type: string
                  description: 有効期限開始
                expiration_out:
                  type: string
                  description: 有効期限終了
                start_time:
                  type: string
                  description: 開始時間
                end_time:
                  type: string
                  description: 終了時間
                available_day_of_week:
                  type: object
                  description: 開放曜日
                  required:
                    - monday
                    - tuesday
                    - wednesday
                    - thursday
                    - friday
                    - saturday
                    - sunday
                  properties:
                    monday:
                      type: boolean
                    tuesday:
                      type: boolean
                    wednesday:
                      type: boolean
                    thursday:
                      type: boolean
                    friday:
                      type: boolean
                    saturday:
                      type: boolean
                    sunday:
                      type: boolean
                reservation_start_date:
                  type: number
                  description: 予約開始日
                equipment:
                  type: string
                  description: 設備
                non_open:
                  type: boolean
                  description: 非開放か
                status:
                  type: number
                  description: '0: 停止 1: 利用可能'
                order_number:
                  type: number
                  description: 表示順
              required:
                - name
                - capacity
                - price
                - expiration_in
                - expiration_out
                - start_time
                - end_time
                - available_day_of_week
                - reservation_start_date
                - status
                - order_number
        description: ''
      security:
        - bearerAuth: []
      description: |-
        部屋追加・編集API
        IDがあれば編集、なければ新規
  '/hotel/rooms/{id}/open_days':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: 部屋ID
    get:
      summary: 開放日一覧
      tags:
        - 部屋
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  open_days:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          description: 日付
                        price:
                          type: number
                          description: 単価
                      required:
                        - date
                        - price
              examples:
                example:
                  value:
                    open_days:
                      - date: 2019/12/12
                        price: 200
                      - date: 2019/12/14
                        price: 250
                      - date: 2019/12/16
                        price: 300
                      - date: 2019/12/18
                        price: 350
                      - date: 2019/12/20
                        price: 400
      operationId: get-hotel-rooms-id-open_days
      description: 開放日一覧取得API
      security:
        - bearerAuth: []
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: date
          description: 年月
          required: true
    post:
      summary: 開放日登録
      tags:
        - 部屋
      responses:
        '200':
          description: OK
      operationId: post-hotel-rooms-id-open_days
      security:
        - bearerAuth: []
      description: 開放日登録API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                open_days:
                  type: array
                  items:
                    type: object
                    properties:
                      date:
                        type: string
                        description: 日付
                      price:
                        type: number
                        description: 単価
                    required:
                      - date
                      - price
              required:
                - open_days
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
tags:
  - name: 認証
    description: ログインに関わるAPI
  - name: ホテル
    description: ホテルAPI
  - name: 部屋
    description: 部屋API
