openapi: 3.0.0
info:
  title: user
  version: '1.0'
  contact:
    name: masashi mizuno
  description: |-
    User向けAPI
    認証はCognitoが発行したJWT Tokenを利用する
servers:
  - url: 'https://satellite-office-app.herokuapp.com'
paths:
  /login:
    post:
      summary: ログイン
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: number
                    description: ログインしたユーザーのID
                    example: 100
                  user_name:
                    type: string
                    description: ユーザー名
                    example: 鈴木太郎
                  token:
                    type: string
                    description: アクセストークン
                    format: string
                    example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
                  is_unauth_user:
                    type: boolean
                    description: |-
                      初回ログインユーザーかどうか
                      初回だった場合はパスワード変更させる
                    example: true
                required:
                  - user_id
                  - user_name
                  - token
                  - is_unauth_user
              examples:
                Example:
                  value:
                    user_id: 1
                    user_name: 太郎
                    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Ai
                    is_unauth_user: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-login
      description: Cognitoを利用した認証を行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 登録メールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - email
                - password
        description: ''
      tags:
        - ユーザー認証
  /change_password:
    post:
      summary: パスワード変更
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-change_password
      description: パスワード変更を行う。初回パスワード設定も
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                  description: 旧パスワード
                new_password:
                  type: string
                  description: 新パスワード
              required:
                - old_password
                - new_password
        description: ''
      tags:
        - ユーザー認証
  /reset_password:
    post:
      summary: パスワードリセット
      tags:
        - ユーザー認証
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reset_password
      description: パスワードリセットを行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      security:
        - bearerAuth: []
  /areas:
    get:
      summary: エリア一覧取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: エリア一覧
                properties:
                  areas:
                    type: array
                    description: エリアリスト
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: エリアID
                        name:
                          type: string
                          description: エリア名
              examples:
                example:
                  value:
                    areas:
                      - id: 1
                        name: 品川
                      - id: 2
                        name: 渋谷
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-areas
      description: エリア一覧を取得する
      tags:
        - 施設関連
      security:
        - bearerAuth: []
  /facilities:
    get:
      summary: 施設一覧
      tags:
        - 施設関連
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result_count:
                    type: number
                    description: 結果件数
                  search_condition:
                    type: string
                    description: 検索条件
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          description: 施設ID
                        name:
                          type: string
                          description: 施設名
                        address:
                          type: string
                          description: 住所
                        tel:
                          type: string
                          description: 電話番号
                        access:
                          type: string
                          description: 交通アクセス
                        parking:
                          type: string
                          description: 駐車場情報
                        url:
                          type: string
                          description: ホテルURL
                        google_map_url:
                          type: string
                          description: GoogleマップURL
                        rooms:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: number
                                description: 部屋ID
                              name:
                                type: string
                                description: 部屋名
                              price:
                                type: string
                                description: 利用単価
                              capacity:
                                type: number
                                description: 座席数
                              sold_out:
                                type: boolean
                                description: 満席かどうか
                      required:
                        - name
                        - address
                required:
                  - result_count
                  - search_condition
              examples:
                example:
                  value:
                    result_count: 3
                    search_condition: 2019/12/31  東京都　品川駅　周辺
                    results:
                      - id: 1
                        name: ホテルA
                        address: 東京都品川区xxxx
                        tel: 03-0000-1111
                        access: ＪＲ線品川駅（高輪口）より徒歩２分
                        parking: '駐車場有り　1,500円（税込み）　先着順'
                        url: 'https://sample.com'
                        google_map_url: 'https://www.google.co.jp/maps/'
                        rooms:
                          - id: 1
                            name: 会議室A
                            price: 200
                            capacity: 20
                            sold_out: true
                          - id: 2
                            name: 会議室B
                            price: 300
                            capacity: 10
                            sold_out: false
                      - id: 2
                        name: ホテルB
                        address: 東京都品川区YYYY
                        tel: 03-0000-3333
                        access: ＪＲ線品川駅（高輪口）より徒歩２分
                        parking: '駐車場有り　1,500円（税込み）　先着順'
                        url: 'https://sample.com'
                        google_map_url: 'https://www.google.co.jp/maps/'
                        rooms:
                          - id: 1
                            name: 会議室A
                            price: 200
                            capacity: 20
                            sold_out: true
                          - id: 2
                            name: 会議室B
                            price: 300
                            capacity: 10
                            sold_out: false
                      - id: 3
                        name: ホテルC
                        address: 東京都品川区ZZZZ
                        tel: 03-0000-4444
                        access: ＪＲ線品川駅（高輪口）より徒歩２分
                        parking: '駐車場有り　1,500円（税込み）　先着順'
                        url: 'https://sample.com'
                        google_map_url: 'https://www.google.co.jp/maps/'
                        rooms:
                          - id: 1
                            name: 会議室A
                            price: 200
                            capacity: 20
                            sold_out: true
                          - id: 2
                            name: 会議室B
                            price: 300
                            capacity: 10
                            sold_out: false
      operationId: get-facilities
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: string
          in: query
          name: date
          description: 日付(yyyy/mm/dd)
          required: true
        - schema:
            type: string
          in: query
          name: range_start_time
          description: 開始時間
        - schema:
            type: string
          in: query
          name: range_end_time
          description: 終了時間
        - schema:
            type: number
          in: query
          name: area_id
          description: エリアID
        - schema:
            type: string
          in: query
          name: station_name
          description: 駅名
      description: 施設一覧API
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      description: ''
tags:
  - name: ユーザー認証
    description: ユーザーログインに関わるAPI
  - name: 施設関連
    description: 施設関連
